<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AdministradoraPlanosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('administradora_planos')->insert([
            [
                'id' => 1,
                'plano_id' => 1,
                'administradora_id' => 4,
                'tabela_origens_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 2,
                'plano_id' => 5,
                'administradora_id' => 4,
                'tabela_origens_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 3,
                'plano_id' => 3,
                'administradora_id' => 1,
                'tabela_origens_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 4,
                'plano_id' => 3,
                'administradora_id' => 2,
                'tabela_origens_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 5,
                'plano_id' => 3,
                'administradora_id' => 3,
                'tabela_origens_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 7,
                'plano_id' => 8,
                'administradora_id' => 2,
                'tabela_origens_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 8,
                'plano_id' => 3,
                'administradora_id' => 2,
                'tabela_origens_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 9,
                'plano_id' => 10,
                'administradora_id' => 4,
                'tabela_origens_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 10,
                'plano_id' => 11,
                'administradora_id' => 4,
                'tabela_origens_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 11,
                'plano_id' => 3,
                'administradora_id' => 2,
                'tabela_origens_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 12,
                'plano_id' => 8,
                'administradora_id' => 2,
                'tabela_origens_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 13,
                'plano_id' => 10,
                'administradora_id' => 4,
                'tabela_origens_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 14,
                'plano_id' => 11,
                'administradora_id' => 4,
                'tabela_origens_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 15,
                'plano_id' => 3,
                'administradora_id' => 2,
                'tabela_origens_id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 16,
                'plano_id' => 8,
                'administradora_id' => 2,
                'tabela_origens_id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 17,
                'plano_id' => 10,
                'administradora_id' => 4,
                'tabela_origens_id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 18,
                'plano_id' => 11,
                'administradora_id' => 4,
                'tabela_origens_id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 19,
                'plano_id' => 3,
                'administradora_id' => 2,
                'tabela_origens_id' => 6,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 20,
                'plano_id' => 8,
                'administradora_id' => 2,
                'tabela_origens_id' => 6,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 21,
                'plano_id' => 10,
                'administradora_id' => 4,
                'tabela_origens_id' => 6,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 22,
                'plano_id' => 11,
                'administradora_id' => 4,
                'tabela_origens_id' => 6,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 23,
                'plano_id' => 3,
                'administradora_id' => 2,
                'tabela_origens_id' => 7,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 24,
                'plano_id' => 8,
                'administradora_id' => 2,
                'tabela_origens_id' => 7,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 25,
                'plano_id' => 10,
                'administradora_id' => 4,
                'tabela_origens_id' => 7,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 26,
                'plano_id' => 11,
                'administradora_id' => 4,
                'tabela_origens_id' => 7,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 27,
                'plano_id' => 1,
                'administradora_id' => 4,
                'tabela_origens_id' => 8,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 28,
                'plano_id' => 3,
                'administradora_id' => 3,
                'tabela_origens_id' => 8,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 29,
                'plano_id' => 5,
                'administradora_id' => 4,
                'tabela_origens_id' => 8,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 31,
                'plano_id' => 1,
                'administradora_id' => 4,
                'tabela_origens_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 32,
                'plano_id' => 3,
                'administradora_id' => 1,
                'tabela_origens_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 33,
                'plano_id' => 5,
                'administradora_id' => 4,
                'tabela_origens_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 34,
                'plano_id' => 10,
                'administradora_id' => 4,
                'tabela_origens_id' => 9,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 35,
                'plano_id' => 11,
                'administradora_id' => 4,
                'tabela_origens_id' => 9,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 36,
                'plano_id' => 14,
                'administradora_id' => 2,
                'tabela_origens_id' => 9,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 37,
                'plano_id' => 8,
                'administradora_id' => 2,
                'tabela_origens_id' => 9,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 38,
                'plano_id' => 3,
                'administradora_id' => 1,
                'tabela_origens_id' => 8,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 39,
                'plano_id' => 3,
                'administradora_id' => 2,
                'tabela_origens_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
        ]);
    }
}
